version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
      - cache
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_TYPE=postgres
      - DATABASE_URL=postgres://user:password@db:5432/devhub
      - REDIS_URL=redis:localhost:6379
    ports:
      - "3000:3000"
    
  db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=devhub
    volumes:
      - dbdata:/var/lib/postgresql/data
  
  cache:
    image: redis
    ports:
      - "6380:6379"

volumes:
  dbdata: