version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
      - cache
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_TYPE=postgres
      - DATABASE_URL=postgres://user:password@postgres:5432/db
      - REDIS_URL=redis:localhost:6379
    ports:
      - "8080:3000"
    
  db:
    image: postgres:13
    ports:
      - "3500:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=devhub
  
  cache:
    image: redis
    ports:
      - "6379:6379"
